Route53resolver - ResolverRuleAssociation
crossplane/provider-aws pull request #679
Opened 2021-05-27 07:14 UTC by AmnaIrfan

### Description of your changes

In this PR we have added the Resolver Rule association resource. This resource falls under the api group "Route53Resolver" which we created in #665 

The previous two resources in #665 (resolverendpoint and resolverrule) were created using codegen. This resource was not available in code gen and was added  manually. 

This resource completes the resolverrule and resolverendpoint resource as it allows users to associate a rule to a vpc.

I have:

- [x]  Read and followed Crossplane's [contribution process].
- [x]  Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested
A sample yaml file can be found under the examples/route53resolver folder. In order to test this resource the user just needs to apply all this file.

Prerequisites: Make sure you set an aws provider, security group, vpc and subnets as well as a resolver endpoint and resolver rule in crossplane before applying this resource.

2021-07-08 23:28 UTC, AmnaIrfan commented
Hey @muvaf -  I was waiting for #665 to be merged. This is now ready for review.
In this PR we add the "resolver rule association" resource to the "route53resolver" api group #665

2021-07-30 07:42 UTC, muvaf reviewed
I have only a few small comments to be adressed. Thank you @AmnaIrfan !

2021-07-30 07:42 UTC, muvaf commented on pkg/controller/route53resolver/resolverruleassociation/controller.go
> +			managed.WithInitializers(managed.NewDefaultProviderConfig(mgr.GetClient())),
```suggestion
			managed.WithInitializers(),
```

That initializer is deprecated and our CRDs handle that defaulting now automatically.

2021-07-30 07:42 UTC, muvaf commented on pkg/controller/route53resolver/resolverruleassociation/controller.go
> +	response, err = e.client.GetResolverRuleAssociationRequest(&awsr53r.GetResolverRuleAssociationInput{
```suggestion
	response, err := e.client.GetResolverRuleAssociationRequest(&awsr53r.GetResolverRuleAssociationInput{
```

2021-07-30 07:42 UTC, muvaf commented on pkg/controller/route53resolver/resolverruleassociation/controller.go
> +		ResourceLateInitialized: !cmp.Equal(current, &cr.Spec.ForProvider),
```suggestion
```
It seems we don't do any late initialization, so it should be fine to return false here.

2021-07-30 07:42 UTC, muvaf commented on pkg/controller/route53resolver/resolverruleassociation/controller.go
> +	cr.Status.AtProvider = r53r.GenerateRoute53ResolverObservation(*observed)
```suggestion
	cr.Status.AtProvider = r53r.GenerateRoute53ResolverObservation(*response.ResolverRuleAssociation)
```

2021-07-30 07:42 UTC, muvaf commented on pkg/controller/route53resolver/resolverruleassociation/controller.go
> +	}
```suggestion
```

We don't need to set conditions for [create](https://github.com/crossplane/crossplane-runtime/blob/master/pkg/reconciler/managed/reconciler.go#L714) and [delete](https://github.com/crossplane/crossplane-runtime/blob/master/pkg/reconciler/managed/reconciler.go#L539) anymore.

2021-07-30 07:42 UTC, muvaf commented on pkg/controller/route53resolver/resolverruleassociation/controller.go
> +	cr.Status.SetConditions(xpv1.Deleting())
```suggestion
```

2021-07-30 07:42 UTC, muvaf commented on pkg/controller/route53resolver/resolverruleassociation/controller.go
> +		return managed.ExternalObservation{}, awsclient.Wrap(resource.Ignore(r53r.IsResolverRuleAssociationNotFoundErr, err), errDescribe)
```suggestion
		return managed.ExternalObservation{}, awsclient.Wrap(err, errDescribe)
```

If the ID is given via external name annotation and the association is not found, we'd normally expect to create an association with that ID. But from what I can tell, association ID is assigned by AWS and cannot be affected by us. So, ignoring `NotFound` will cause us to create a new resource and override the given ID, which is probably not something user wants if they give the ID. So, ignoring the error here makes more sense if the identifier we use can be decided by us. I know some resources similar to this one do ignore but that's due to historical reasons.

2021-08-04 20:44 UTC, AmnaIrfan commented
@muvaf  Thank you for the review.  Please let me know if I need to do anymore changes. Thank you!

2021-09-30 03:12 UTC, AaronME requested changes
@AmnaIrfan Thank you for the PR!

I was unable to get a working build from the branch until I removed `errStatusUpdate.` With that removed it builds, but I didn't get a successful creation of a resolverruleassociation resource.

To get this approved we need:
- Rebase on current `master`
- Add `route53resolver` to the list of GENERATED_SERVICES in the [Makefile](https://github.com/crossplane/provider-aws/blob/988e66c6befcb6b6e7ce575d56f8254683aa442b/Makefile#L10)
- Run `make reviewable` before pushing.

Thanks, again!

2021-12-14 17:22 UTC, haarchri commented
i was not aware of this PR i added the same resource https://github.com/crossplane/provider-aws/pull/968 - i can close my PR if we go to merge this one

2022-01-29 12:25 UTC, haarchri commented
implemented via https://github.com/crossplane/provider-aws/pull/968

2022-01-29 12:25 UTC, closed without merging