Fix Address descriptions
crossplane/provider-aws pull request #757
Opened 2021-07-05 14:35 UTC by dweebo

### Description of your changes

Update a few of the descriptions for the `addresses.ec2.aws.crossplane.io` CRD.
Refer to EIPs instead of VPC.  

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Since it is just documentation I have not done any testing

2021-07-05 14:39 UTC, hasheddan requested changes
Hey @dweebo, thanks for the PR! We actually generate these description fields from the doc strings on the structs, so they will need to be updated there, then you can run `make generate` to reflect them here. For example, you would update this doc string for `Region`: https://github.com/crossplane/provider-aws/blob/36e425acdcb52a670f78ab5e37b8f81864d3f393/apis/ec2/v1beta1/address_types.go#L27

2021-07-05 15:17 UTC, dweebo commented
> Hey @dweebo, thanks for the PR! We actually generate these description fields from the doc strings on the structs, so they will need to be updated there, then you can run `make generate` to reflect them here. For example, you would update this doc string for `Region`:
> 
> https://github.com/crossplane/provider-aws/blob/36e425acdcb52a670f78ab5e37b8f81864d3f393/apis/ec2/v1beta1/address_types.go#L27

Ah yes of course.  Fixed now.

2021-07-05 19:39 UTC, hasheddan commented on apis/ec2/v1beta1/address_types.go
> +// A Address is a managed resource that represents an AWS Elastic IP Address.
nitpick:
```suggestion
// An Address is a managed resource that represents an AWS Elastic IP Address.
```

2021-07-06 11:23 UTC, hasheddan approved these changes
Thanks @dweebo!

2021-07-06 11:43 UTC, merged