owners: add new maintainers
crossplane/provider-aws pull request #786
Opened 2021-07-30 09:06 UTC by muvaf

### Description of your changes

Adding @turkenh and @ulucinar as maintainers.

### How has this code been tested

N/A

[contribution process]: https://git.io/fj2m9

2021-07-30 09:46 UTC, hasheddan approved these changes

2021-07-31 02:44 UTC, jbw976 requested changes
Can we add @AaronME to this list as well?  He has been providing high quality reviews of PRs recently and keeping the quality level and coding standards at a high level.  He's also making a long term commitment to the project, so is a great candidate for maintainer, similar to Hasan and Alper.

2021-08-03 23:27 UTC, negz approved these changes

2021-08-05 00:32 UTC, jbw976 approved these changes

2021-08-05 00:32 UTC, merged

2021-08-05 00:35 UTC, jbw976 commented
I've added all new maintainers to the repository permissions with `Maintainer` access.  Congratulations @turkenh @AaronME @ulucinar and thank you for your contributions and commitment to the project! 🙇‍♂️