Add subnet tag controller for subnet tags
crossplane/provider-aws pull request #822
Opened 2021-09-07 12:37 UTC by MisterMX

### Description of your changes

Fixes #692 

This PR adds a new `SubnetTag` resource that allows tagging an AWS Subnet without using the Crossplane `Subnet` resource.

I have:

- [x] Read and followed Crossplane's [contribution process].
- [x] Run `make reviewable test` to ensure this PR is ready for review.

### How has this code been tested

Manually

2021-09-08 12:53 UTC, MisterMX commented
Updated this PR to a generic `ResourceTag` instead of the specific `SubnetTag` resource to better match the AWS API.

2021-09-12 19:13 UTC, janwillies requested changes
Thanks @MisterMX! I wonder if this API should be simply called `Tags`, since `ResourceTags` can be confused with the [Resource Groups Tagging API](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/resourcegroupstaggingapi)?

2021-09-13 14:31 UTC, MisterMX commented on examples/ec2/subnettag.yaml
> +kind: SubnetTag
No its a leftover from refactoring. Thanks for mentioning it. I corrected it.

2021-09-13 14:32 UTC, MisterMX commented on apis/ec2/manualv1alpha1/referencers.go
> +// func (mg *VPCCIDRBlock) ResolveReferences(ctx context.Context, c client.Reader) error {
No that a mistake by me. This part shouldn't be changed at all. I removed the changes.

2021-09-13 14:34 UTC, MisterMX commented on apis/ec2/manualv1alpha1/resource_tag.go
> +Copyright 2019 The Crossplane Authors.
Fixed

2021-09-13 14:39 UTC, MisterMX commented
@janwillies I understand what you mean. The name is quite generic. Though the AWS API also just calls it `CreateTags` and `DeleteTags`. Do you have a suggestion for a less ambiguous name?

2021-09-14 12:12 UTC, janwillies commented
Looking at the ec2 api I believe it should be `tags`, but I'll defer to @chlunde who has much more knowledge in this area.

2021-09-15 16:51 UTC, haarchri commented on apis/ec2/manualv1alpha1/register.go
> +// SubnatTag type metadata.
`// SubnetTag type metadata.`

2021-09-15 17:03 UTC, chlunde commented
Assigning @negz / @muvaf because I think this needs a design review. A generic EC2 Tags resource does have some nice use cases, but it will cause issues if the resource is managed by another crossplane controller - and possibly also if it is managed by terraform or another tool, so I think we need to think this through.

2021-09-15 18:06 UTC, chlunde commented
_just thinking out loud here:_

This resource type should strive to co-exist with other features (at least that might be a mode). So if another resource is tagged `{t0: foo, t1: foo}` and the user requests `{t2: faz}`, I think most people would want the resource to be tagged `{t0: foo, t1: foo, t2: faz}`. If you delete the resource, only the `t2` tag should be removed.

One way to achieve this would be to have a status field `ownedTags: [t2]`, meaning that we would only reconcile the tags we "own".

This might have to be put behind a flag under `spec`, because there might be other useful modes:
* take full ownership of tags using this controller.
* initially take full ownership, then move to "merge" mode
* merge mode from start
* define a tag prefix and take full ownership under that prefix

Possibly there should be a way to delete a tag (written by other tools) even in "merge" mode, it might be possible to use the nil/undefined tag value for this.

And this might work well with [terraform w/ ignore_changes](https://www.terraform.io/docs/language/meta-arguments/lifecycle.html#ignore_changes), but it does not work with crossplane. So maybe this `tag mode` think should exist for *all* (AWS) resources?

2021-09-15 23:05 UTC, negz commented on apis/ec2/manualv1alpha1/resource_tag.go
> +	// +optionial
```suggestion
	// +optional
```

2021-09-15 23:06 UTC, negz commented on apis/ec2/manualv1alpha1/resource_tag.go
> +	// AtProvider          ResourceTagObservation `json:"atProvider,omitempty"`
```suggestion
```

2021-09-15 23:08 UTC, negz commented
Thanks for the tag @chlunde. I agree this pattern needs discussion. It's a novel concept that I believe goes against how we've historically handled other resources in this provider - i.e. I believe we often model tags as a property of other managed resources (which is arguably a less faithful representation of the AWS API than the approach in this PR).

One shortcoming of this approach is that with our current reference resolution pattern I imagine it would be impossible to ever have an array of `resourceIdRef` or a `resourceIdsSelector`, because the referenced resources would be of arbitrary type (and iirc not all AWS resources can be tagged).

2021-09-16 14:46 UTC, MisterMX commented
@chlunde  @negz many controllers follow the `add, remove` pattern and will delete any tags from the resource they don't know, except for `Subnet` which only every adds new tags to a resource - it also was the initial purpose of this PR before I rewrote it to be more generic (hence the title).

I really like the idea of a `tagMode` field which would make this resource much more flexible.

2022-02-01 12:44 UTC, MisterMX commented
Since Subnet Tags are not needed anymore for load balancers this PR is obsolete and can be closed.

2022-02-01 12:44 UTC, closed without merging

2022-06-30 07:25 UTC, haarchri commented
we have a use-case for this PR
we need to Tag for Karpenter the EKS generated SecurityGroup 
https://karpenter.sh/v0.13.1/getting-started/migrating-from-cas/#add-tags-to-subnets-and-security-groups

```
NODEGROUP=$(aws eks list-nodegroups --cluster-name ${CLUSTER_NAME} \
    --query 'nodegroups[0]' --output text)

LAUNCH_TEMPLATE=$(aws eks describe-nodegroup --cluster-name ${CLUSTER_NAME} \
    --nodegroup-name ${NODEGROUP} --query 'nodegroup.launchTemplate.{id:id,version:version}' \
    --output text | tr -s "\t" ",")

SECURITY_GROUPS=$(aws ec2 describe-launch-template-versions \
    --launch-template-id ${LAUNCH_TEMPLATE%,*} --versions ${LAUNCH_TEMPLATE#*,} \
    --query 'LaunchTemplateVersions[0].LaunchTemplateData.SecurityGroupIds' \
    --output text)

aws ec2 create-tags \
    --tags "Key=karpenter.sh/discovery,Value=${CLUSTER_NAME}" \
    --resources ${SECURITY_GROUPS}
```

we can get the sg from `kubectl describe cluster.eks.aws.crossplane.io/crossplane-dev-dr9p7-98594` status.atProvider.resourcesVpcConfig.clusterSecurityGroupId: `sg-08c821268fffc30aa` but we have no chance without this PR to tag the SG 

in jet-provider we have the same resource https://doc.crds.dev/github.com/crossplane-contrib/provider-jet-aws/ec2.aws.jet.crossplane.io/Tag/v1alpha1@v0.4.0-preview#spec-forProvider 

for me +1 to go forward with Tag Resource

2022-06-30 07:51 UTC, haarchri commented
we can add a few comments like terraform

`Manages an individual EC2 resource tag. This resource should only be used in cases where EC2 resources are created outside Crossplane (e.g., AMIs), being shared via Resource Access Manager (RAM), or implicitly created by other means (e.g., Transit Gateway VPN Attachments, EKS ClusterSecurityGroup).`

`This tagging resource should not be combined with the crossplane resource for managing the parent resource. For example, using vpc and tagresource to manage tags of the same VPC will cause a perpetual difference where the vpc resource will try to remove the tag being added by the tagresource.`

2022-10-05 19:36 UTC, zetamorph commented
Hi 👋 
is there any chance we can re-open this? 
We have the same use case as the one @haarchri described [above](https://github.com/crossplane-contrib/provider-aws/pull/822#issuecomment-1170863716): we want to tag the security groups that are created automatically when EKS clusters are created.

Currently we're using provider-jet-aws with it's `Tag` resource to handle this.

2022-10-05 20:24 UTC, zetamorph commented
Another possible use case is as follows:

EKS Managed Nodegroups each have an underlying EC2 Autoscaling group. We need to control the tags of these ASGs.
By using a Launchtemplate and configuring `tagSpecifications`, we can apply tags to the EC2 instances managed by the ASG. However, these tags are not applied to the ASG, just the instances.

This is a shortcoming of the AWS API, see also [this issue](https://github.com/aws/containers-roadmap/issues/608), but since it doesn't look like the issue will be resolved soon, the ability to tag arbitrary resources using `provider-aws` would be really helpful.

2022-10-17 07:50 UTC, MisterMX commented
> is there any chance we can re-open this?

@zetamorph unfortunately, I don't have the time to work on this issue. But feel free reuse my changes if you have a use case.